import Head from 'next/head';
import { Inter } from '@next/font/google';
import LandingPage from './components/landing-page';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PT Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/primeicons/primeicons.css"
        />
      </Head>
      <main>
        <LandingPage />
      </main>
    </>
  );
}
