import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Points System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/primeicons/primeicons.css" />
      </Head>
      <main>
        <a href='sign-in'>Sign In</a>
        <a href='sign-up'>Sign Up</a>
      </main>
    </>
  )
}
